version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}

      - run: npm install
      - run: npm run check-all
      - run: npm run codecov

      - save_cache:
          paths:
            - ./node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: npm pack

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

      - store_artifacts:
          path: artifacts

  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Run release
          command: npm run semantic-release

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /master/
